replicas:
  auth: 1
  users: 1
  tasks: 1
  frontend: 1

images:
  auth: aleksandromilenkov/kub-demo-auth:v1.0.1763828722
  users: aleksandromilenkov/kub-demo-users:v1.0.1763828723
  tasks: aleksandromilenkov/kub-demo-tasks:v1.0.1763828723
  frontend: aleksandromilenkov/kub-demo-frontend:v1.0.1763828723

services:
  auth:
    port: 80
  users:
    port: 8080
  tasks:
    port: 8000
  frontend:
    port: 80

ingress:
  host: "myapp.local"

config:
  AUTH_SERVICE_URL: "http://auth-service"
  USER_SERVICE_URL: "http://user-service:8080"
  TASKS_SERVICE_URL: "http://tasks-service:8000"
  EXTERNAL_AUTH_URL: "http://myapp.local/auth"
  EXTERNAL_USER_URL: "http://myapp.local/users"
  EXTERNAL_TASKS_URL: "http://myapp.local/tasks"

secret:
  DUMMY_SECRET: "some dummy fake secret"
