apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tasks
spec:
  replicas: {{ .Values.replicas.tasks }}
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: {{ .Values.images.tasks }}
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
          env:
            - name: TASKS_FOLDER
              value: tasks
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL